using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Team1922.MVVM.Models;

namespace Team1922.MVVM.Contracts
{
    /// <summary>
    /// The interface for a robot map viewmodel
    /// The robot map is for additional constants that do not fit into the existing constants in other objects
    /// </summary>
    public interface IRobotMapProvider : IProvider
    {
        /// <summary>
        /// Sets the robot model instance for this robot map
        /// </summary>
        /// <param name="robot">the main robot instance</param>
        void SetRobot(Robot robot);
        /// <summary>
        /// Adds a new entry into the map
        /// </summary>
        /// <remarks>
        /// if <paramref name="key"/> is blank, a key should be autogenerated that is guaranteed to be unique
        /// </remarks>
        /// <param name="key">the name used to reference the value</param>
        /// <param name="value">the value referenced by <paramref name="key"/></param>
        void AddEntry(string key, string value);
    }
}
