//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 

namespace Team1922.MVVM.Models
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
#if NET461
    [System.ComponentModel.DesignerCategoryAttribute("code")]
#endif
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/RobotSchema.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/RobotSchema.xsd", IsNullable = false)]
    public partial class Robot
    {

        private object[] itemsField;

        private string teamNumberField;

        private string analogInputSampleRateField;

        public Robot()
        {
            this.analogInputSampleRateField = "62500";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ContinuousCommand", typeof(ContinuousCommand))]
        [System.Xml.Serialization.XmlElementAttribute("Joystick", typeof(Joystick))]
        [System.Xml.Serialization.XmlElementAttribute("OnChangeEventHandler", typeof(OnChangeEventHandler))]
        [System.Xml.Serialization.XmlElementAttribute("OnWithinRangeEventHandler", typeof(OnWithinRangeEventHandler))]
        [System.Xml.Serialization.XmlElementAttribute("Subsystem", typeof(Subsystem))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "positiveInteger")]
        public string TeamNumber
        {
            get
            {
                return this.teamNumberField;
            }
            set
            {
                this.teamNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "positiveInteger")]
        [System.ComponentModel.DefaultValueAttribute("62500")]
        public string AnalogInputSampleRate
        {
            get
            {
                return this.analogInputSampleRateField;
            }
            set
            {
                this.analogInputSampleRateField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
#if NET461
    [System.ComponentModel.DesignerCategoryAttribute("code")]
#endif
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/RobotSchema.xsd")]
    public partial class ContinuousCommand
    {

        private object itemField;

        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FullCSMethod", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("ModifyValue", typeof(ModifyValueHandler))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
#if NET461
    [System.ComponentModel.DesignerCategoryAttribute("code")]
#endif
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/RobotSchema.xsd")]
    public partial class ModifyValueHandler
    {

        private string arithOpField;

        private string modifyPathField;

        /// <remarks/>
        public string ArithOp
        {
            get
            {
                return this.arithOpField;
            }
            set
            {
                this.arithOpField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ModifyPath
        {
            get
            {
                return this.modifyPathField;
            }
            set
            {
                this.modifyPathField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
#if NET461
    [System.ComponentModel.DesignerCategoryAttribute("code")]
#endif
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/RobotSchema.xsd")]
    public partial class JoystickButton
    {

        private string idField;

        private bool valueField;

        public JoystickButton()
        {
            this.valueField = false;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
#if NET461
    [System.ComponentModel.DesignerCategoryAttribute("code")]
#endif
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/RobotSchema.xsd")]
    public partial class JoystickAxis
    {

        private string idField;

        private double valueField;

        public JoystickAxis()
        {
            this.valueField = 0D;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0D)]
        public double Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
#if NET461
    [System.ComponentModel.DesignerCategoryAttribute("code")]
#endif
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/RobotSchema.xsd")]
    public partial class Joystick
    {

        private JoystickAxis[] axisField;

        private JoystickButton[] buttonField;

        private string nameField;

        private string idField;

        public Joystick()
        {
            this.idField = "-1";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Axis")]
        public JoystickAxis[] Axis
        {
            get
            {
                return this.axisField;
            }
            set
            {
                this.axisField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Button")]
        public JoystickButton[] Button
        {
            get
            {
                return this.buttonField;
            }
            set
            {
                this.buttonField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "token")]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        [System.ComponentModel.DefaultValueAttribute("-1")]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
#if NET461
    [System.ComponentModel.DesignerCategoryAttribute("code")]
#endif
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/RobotSchema.xsd")]
    public partial class OnWithinRangeEventHandler
    {

        private object itemField;

        private string nameField;

        private string watchPathField;

        private double minField;

        private double maxField;

        private bool invertField;

        public OnWithinRangeEventHandler()
        {
            this.invertField = false;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FullCSMethod", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("ModifyValue", typeof(ModifyValueHandler))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string WatchPath
        {
            get
            {
                return this.watchPathField;
            }
            set
            {
                this.watchPathField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double Min
        {
            get
            {
                return this.minField;
            }
            set
            {
                this.minField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double Max
        {
            get
            {
                return this.maxField;
            }
            set
            {
                this.maxField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Invert
        {
            get
            {
                return this.invertField;
            }
            set
            {
                this.invertField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
#if NET461
    [System.ComponentModel.DesignerCategoryAttribute("code")]
#endif
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/RobotSchema.xsd")]
    public partial class OnChangeEventHandler
    {

        private object itemField;

        private string nameField;

        private string watchPathField;

        private double minDeltaField;

        public OnChangeEventHandler()
        {
            this.minDeltaField = 0D;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FullCSMethod", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("ModifyValue", typeof(ModifyValueHandler))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string WatchPath
        {
            get
            {
                return this.watchPathField;
            }
            set
            {
                this.watchPathField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0D)]
        public double MinDelta
        {
            get
            {
                return this.minDeltaField;
            }
            set
            {
                this.minDeltaField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
#if NET461
    [System.ComponentModel.DesignerCategoryAttribute("code")]
#endif
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/RobotSchema.xsd")]
    public partial class PIDControllerSoftware
    {

        private double pField;

        private bool pFieldSpecified;

        private double iField;

        private bool iFieldSpecified;

        private double dField;

        private bool dFieldSpecified;

        private double fField;

        private bool fFieldSpecified;

        private double toleranceField;

        private bool toleranceFieldSpecified;

        private double cycleDurationField;

        private bool cycleDurationFieldSpecified;

        private bool continuousField;

        private bool continuousFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double P
        {
            get
            {
                return this.pField;
            }
            set
            {
                this.pField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PSpecified
        {
            get
            {
                return this.pFieldSpecified;
            }
            set
            {
                this.pFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double I
        {
            get
            {
                return this.iField;
            }
            set
            {
                this.iField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ISpecified
        {
            get
            {
                return this.iFieldSpecified;
            }
            set
            {
                this.iFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double D
        {
            get
            {
                return this.dField;
            }
            set
            {
                this.dField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DSpecified
        {
            get
            {
                return this.dFieldSpecified;
            }
            set
            {
                this.dFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double F
        {
            get
            {
                return this.fField;
            }
            set
            {
                this.fField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FSpecified
        {
            get
            {
                return this.fFieldSpecified;
            }
            set
            {
                this.fFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double Tolerance
        {
            get
            {
                return this.toleranceField;
            }
            set
            {
                this.toleranceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ToleranceSpecified
        {
            get
            {
                return this.toleranceFieldSpecified;
            }
            set
            {
                this.toleranceFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double CycleDuration
        {
            get
            {
                return this.cycleDurationField;
            }
            set
            {
                this.cycleDurationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CycleDurationSpecified
        {
            get
            {
                return this.cycleDurationFieldSpecified;
            }
            set
            {
                this.cycleDurationFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Continuous
        {
            get
            {
                return this.continuousField;
            }
            set
            {
                this.continuousField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ContinuousSpecified
        {
            get
            {
                return this.continuousFieldSpecified;
            }
            set
            {
                this.continuousFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
#if NET461
    [System.ComponentModel.DesignerCategoryAttribute("code")]
#endif
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/RobotSchema.xsd")]
    public partial class PIDControllerSRX
    {

        private double pField;

        private bool pFieldSpecified;

        private double iField;

        private bool iFieldSpecified;

        private double dField;

        private bool dFieldSpecified;

        private double fField;

        private bool fFieldSpecified;

        private int iZoneField;

        private bool iZoneFieldSpecified;

        private double closeLoopRampRateField;

        private bool closeLoopRampRateFieldSpecified;

        private int allowableCloseLoopErrorField;

        private bool allowableCloseLoopErrorFieldSpecified;

        private CANTalonDifferentiationLevel sourceTypeField;

        private bool sourceTypeFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double P
        {
            get
            {
                return this.pField;
            }
            set
            {
                this.pField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PSpecified
        {
            get
            {
                return this.pFieldSpecified;
            }
            set
            {
                this.pFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double I
        {
            get
            {
                return this.iField;
            }
            set
            {
                this.iField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ISpecified
        {
            get
            {
                return this.iFieldSpecified;
            }
            set
            {
                this.iFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double D
        {
            get
            {
                return this.dField;
            }
            set
            {
                this.dField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DSpecified
        {
            get
            {
                return this.dFieldSpecified;
            }
            set
            {
                this.dFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double F
        {
            get
            {
                return this.fField;
            }
            set
            {
                this.fField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FSpecified
        {
            get
            {
                return this.fFieldSpecified;
            }
            set
            {
                this.fFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int IZone
        {
            get
            {
                return this.iZoneField;
            }
            set
            {
                this.iZoneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IZoneSpecified
        {
            get
            {
                return this.iZoneFieldSpecified;
            }
            set
            {
                this.iZoneFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double CloseLoopRampRate
        {
            get
            {
                return this.closeLoopRampRateField;
            }
            set
            {
                this.closeLoopRampRateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CloseLoopRampRateSpecified
        {
            get
            {
                return this.closeLoopRampRateFieldSpecified;
            }
            set
            {
                this.closeLoopRampRateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int AllowableCloseLoopError
        {
            get
            {
                return this.allowableCloseLoopErrorField;
            }
            set
            {
                this.allowableCloseLoopErrorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AllowableCloseLoopErrorSpecified
        {
            get
            {
                return this.allowableCloseLoopErrorFieldSpecified;
            }
            set
            {
                this.allowableCloseLoopErrorFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public CANTalonDifferentiationLevel SourceType
        {
            get
            {
                return this.sourceTypeField;
            }
            set
            {
                this.sourceTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SourceTypeSpecified
        {
            get
            {
                return this.sourceTypeFieldSpecified;
            }
            set
            {
                this.sourceTypeFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/RobotSchema.xsd")]
    public enum CANTalonDifferentiationLevel
    {

        /// <remarks/>
        Displacement,

        /// <remarks/>
        Speed,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
#if NET461
    [System.ComponentModel.DesignerCategoryAttribute("code")]
#endif
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/RobotSchema.xsd")]
    public partial class CANTalon
    {

        private object itemField;

        private QuadEncoder quadEncoderField;

        private PIDControllerSRX pIDConfig0Field;

        private PIDControllerSRX pIDConfig1Field;

        private string idField;

        private string nameField;

        private bool enabledPIDProfileField;

        private CANTalonFeedbackDevice feedbackDeviceField;

        private CANTalonControlMode controlModeField;

        private CANTalonNeutralMode neutralModeField;

        private bool zeroSensorPositionOnIndexEnabledField;

        private bool zeroSensorPositionOnRisingEdgeField;

        private bool reverseSensorField;

        private bool reverseClosedLoopOutputField;

        private bool reversePercentVBusOutputField;

        private bool forwardLimitSwitchEnabledField;

        private bool reverseLimitSwitchEnabledField;

        private bool forwardSoftLimitEnabledField;

        private bool reverseSoftLimitEnabledField;

        private double forwardSoftLimitField;

        private double reverseSoftLimitField;

        private double nominalForwardVoltageField;

        private double nominalReverseVoltageField;

        private double peakForwardVoltageField;

        private double peakReverseVoltageField;

        private double valueField;

        public CANTalon()
        {
            this.idField = "-1";
            this.enabledPIDProfileField = false;
            this.feedbackDeviceField = CANTalonFeedbackDevice.QuadEncoder;
            this.controlModeField = CANTalonControlMode.PercentVbus;
            this.neutralModeField = CANTalonNeutralMode.Coast;
            this.zeroSensorPositionOnIndexEnabledField = false;
            this.zeroSensorPositionOnRisingEdgeField = false;
            this.reverseSensorField = false;
            this.reverseClosedLoopOutputField = false;
            this.reversePercentVBusOutputField = false;
            this.forwardLimitSwitchEnabledField = false;
            this.reverseLimitSwitchEnabledField = false;
            this.forwardSoftLimitEnabledField = false;
            this.reverseSoftLimitEnabledField = false;
            this.forwardSoftLimitField = 0D;
            this.reverseSoftLimitField = 0D;
            this.nominalForwardVoltageField = 0D;
            this.nominalReverseVoltageField = 0D;
            this.peakForwardVoltageField = 12D;
            this.peakReverseVoltageField = -12D;
            this.valueField = 0D;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AnalogInput", typeof(AnalogInput))]
        [System.Xml.Serialization.XmlElementAttribute("Potentiometer", typeof(Potentiometer))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        public QuadEncoder QuadEncoder
        {
            get
            {
                return this.quadEncoderField;
            }
            set
            {
                this.quadEncoderField = value;
            }
        }

        /// <remarks/>
        public PIDControllerSRX PIDConfig0
        {
            get
            {
                return this.pIDConfig0Field;
            }
            set
            {
                this.pIDConfig0Field = value;
            }
        }

        /// <remarks/>
        public PIDControllerSRX PIDConfig1
        {
            get
            {
                return this.pIDConfig1Field;
            }
            set
            {
                this.pIDConfig1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        [System.ComponentModel.DefaultValueAttribute("-1")]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "token")]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool EnabledPIDProfile
        {
            get
            {
                return this.enabledPIDProfileField;
            }
            set
            {
                this.enabledPIDProfileField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(CANTalonFeedbackDevice.QuadEncoder)]
        public CANTalonFeedbackDevice FeedbackDevice
        {
            get
            {
                return this.feedbackDeviceField;
            }
            set
            {
                this.feedbackDeviceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(CANTalonControlMode.PercentVbus)]
        public CANTalonControlMode ControlMode
        {
            get
            {
                return this.controlModeField;
            }
            set
            {
                this.controlModeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(CANTalonNeutralMode.Coast)]
        public CANTalonNeutralMode NeutralMode
        {
            get
            {
                return this.neutralModeField;
            }
            set
            {
                this.neutralModeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ZeroSensorPositionOnIndexEnabled
        {
            get
            {
                return this.zeroSensorPositionOnIndexEnabledField;
            }
            set
            {
                this.zeroSensorPositionOnIndexEnabledField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ZeroSensorPositionOnRisingEdge
        {
            get
            {
                return this.zeroSensorPositionOnRisingEdgeField;
            }
            set
            {
                this.zeroSensorPositionOnRisingEdgeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ReverseSensor
        {
            get
            {
                return this.reverseSensorField;
            }
            set
            {
                this.reverseSensorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ReverseClosedLoopOutput
        {
            get
            {
                return this.reverseClosedLoopOutputField;
            }
            set
            {
                this.reverseClosedLoopOutputField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ReversePercentVBusOutput
        {
            get
            {
                return this.reversePercentVBusOutputField;
            }
            set
            {
                this.reversePercentVBusOutputField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ForwardLimitSwitchEnabled
        {
            get
            {
                return this.forwardLimitSwitchEnabledField;
            }
            set
            {
                this.forwardLimitSwitchEnabledField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ReverseLimitSwitchEnabled
        {
            get
            {
                return this.reverseLimitSwitchEnabledField;
            }
            set
            {
                this.reverseLimitSwitchEnabledField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ForwardSoftLimitEnabled
        {
            get
            {
                return this.forwardSoftLimitEnabledField;
            }
            set
            {
                this.forwardSoftLimitEnabledField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ReverseSoftLimitEnabled
        {
            get
            {
                return this.reverseSoftLimitEnabledField;
            }
            set
            {
                this.reverseSoftLimitEnabledField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0D)]
        public double ForwardSoftLimit
        {
            get
            {
                return this.forwardSoftLimitField;
            }
            set
            {
                this.forwardSoftLimitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0D)]
        public double ReverseSoftLimit
        {
            get
            {
                return this.reverseSoftLimitField;
            }
            set
            {
                this.reverseSoftLimitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0D)]
        public double NominalForwardVoltage
        {
            get
            {
                return this.nominalForwardVoltageField;
            }
            set
            {
                this.nominalForwardVoltageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0D)]
        public double NominalReverseVoltage
        {
            get
            {
                return this.nominalReverseVoltageField;
            }
            set
            {
                this.nominalReverseVoltageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(12D)]
        public double PeakForwardVoltage
        {
            get
            {
                return this.peakForwardVoltageField;
            }
            set
            {
                this.peakForwardVoltageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(-12D)]
        public double PeakReverseVoltage
        {
            get
            {
                return this.peakReverseVoltageField;
            }
            set
            {
                this.peakReverseVoltageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0D)]
        public double Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
#if NET461
    [System.ComponentModel.DesignerCategoryAttribute("code")]
#endif
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/RobotSchema.xsd")]
    public partial class AnalogInput
    {

        private string idField;

        private string nameField;

        private int accumulatorCenterField;

        private int accumulatorDeadBandField;

        private int accumulatorInitialValueField;

        private int averageBitsField;

        private int oversampleBitsField;

        private double conversionRatioField;

        private double sensorOffsetField;

        private int rawInputField;

        private double convertedInputField;

        public AnalogInput()
        {
            this.idField = "-1";
            this.accumulatorCenterField = 2048;
            this.accumulatorInitialValueField = 0;
            this.conversionRatioField = 1D;
            this.sensorOffsetField = 0D;
            this.rawInputField = 0;
            this.convertedInputField = 0D;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        [System.ComponentModel.DefaultValueAttribute("-1")]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "token")]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(2048)]
        public int AccumulatorCenter
        {
            get
            {
                return this.accumulatorCenterField;
            }
            set
            {
                this.accumulatorCenterField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int accumulatorDeadBand
        {
            get
            {
                return this.accumulatorDeadBandField;
            }
            set
            {
                this.accumulatorDeadBandField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int AccumulatorInitialValue
        {
            get
            {
                return this.accumulatorInitialValueField;
            }
            set
            {
                this.accumulatorInitialValueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int AverageBits
        {
            get
            {
                return this.averageBitsField;
            }
            set
            {
                this.averageBitsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int OversampleBits
        {
            get
            {
                return this.oversampleBitsField;
            }
            set
            {
                this.oversampleBitsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(1D)]
        public double ConversionRatio
        {
            get
            {
                return this.conversionRatioField;
            }
            set
            {
                this.conversionRatioField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0D)]
        public double SensorOffset
        {
            get
            {
                return this.sensorOffsetField;
            }
            set
            {
                this.sensorOffsetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int RawInput
        {
            get
            {
                return this.rawInputField;
            }
            set
            {
                this.rawInputField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0D)]
        public double ConvertedInput
        {
            get
            {
                return this.convertedInputField;
            }
            set
            {
                this.convertedInputField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
#if NET461
    [System.ComponentModel.DesignerCategoryAttribute("code")]
#endif
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/RobotSchema.xsd")]
    public partial class Potentiometer
    {

        private string idField;

        private string nameField;

        private double conversionRatioField;

        private double sensorOffsetField;

        private int rawValueField;

        private double valueField;

        public Potentiometer()
        {
            this.idField = "-1";
            this.conversionRatioField = 1D;
            this.sensorOffsetField = 0D;
            this.rawValueField = 0;
            this.valueField = 0D;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        [System.ComponentModel.DefaultValueAttribute("-1")]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "token")]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(1D)]
        public double ConversionRatio
        {
            get
            {
                return this.conversionRatioField;
            }
            set
            {
                this.conversionRatioField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0D)]
        public double SensorOffset
        {
            get
            {
                return this.sensorOffsetField;
            }
            set
            {
                this.sensorOffsetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int RawValue
        {
            get
            {
                return this.rawValueField;
            }
            set
            {
                this.rawValueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0D)]
        public double Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
#if NET461
    [System.ComponentModel.DesignerCategoryAttribute("code")]
#endif
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/RobotSchema.xsd")]
    public partial class QuadEncoder
    {

        private string idField;

        private string iD1Field;

        private string nameField;

        private double conversionRatioField;

        private long rawValueField;

        private double valueField;

        private double rawVelocityField;

        private double velocityField;

        public QuadEncoder()
        {
            this.idField = "-1";
            this.iD1Field = "-1";
            this.conversionRatioField = 1D;
            this.rawValueField = ((long)(0));
            this.valueField = 0D;
            this.rawVelocityField = 0D;
            this.velocityField = 0D;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        [System.ComponentModel.DefaultValueAttribute("-1")]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        [System.ComponentModel.DefaultValueAttribute("-1")]
        public string ID1
        {
            get
            {
                return this.iD1Field;
            }
            set
            {
                this.iD1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "token")]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(1D)]
        public double ConversionRatio
        {
            get
            {
                return this.conversionRatioField;
            }
            set
            {
                this.conversionRatioField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(long), "0")]
        public long RawValue
        {
            get
            {
                return this.rawValueField;
            }
            set
            {
                this.rawValueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0D)]
        public double Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0D)]
        public double RawVelocity
        {
            get
            {
                return this.rawVelocityField;
            }
            set
            {
                this.rawVelocityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0D)]
        public double Velocity
        {
            get
            {
                return this.velocityField;
            }
            set
            {
                this.velocityField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/RobotSchema.xsd")]
    public enum CANTalonFeedbackDevice
    {

        /// <remarks/>
        QuadEncoder,

        /// <remarks/>
        AnalogPotentiometer,

        /// <remarks/>
        AnalogEncoder,

        /// <remarks/>
        EncoderRising,

        /// <remarks/>
        EncoderFalling,

        /// <remarks/>
        CtreMagEncoderRelative,

        /// <remarks/>
        CtreMagEncoderAbsolute,

        /// <remarks/>
        PulseWidth,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/RobotSchema.xsd")]
    public enum CANTalonControlMode
    {

        /// <remarks/>
        PercentVbus,

        /// <remarks/>
        Position,

        /// <remarks/>
        Speed,

        /// <remarks/>
        Current,

        /// <remarks/>
        Voltage,

        /// <remarks/>
        Follower,

        /// <remarks/>
        MotionProfile,

        /// <remarks/>
        Disabled,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/RobotSchema.xsd")]
    public enum CANTalonNeutralMode
    {

        /// <remarks/>
        Jumper,

        /// <remarks/>
        Brake,

        /// <remarks/>
        Coast,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
#if NET461
    [System.ComponentModel.DesignerCategoryAttribute("code")]
#endif
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/RobotSchema.xsd")]
    public partial class RelayOutput
    {

        private string idField;

        private string nameField;

        private RelayDirection directionField;

        private RelayValue valueField;

        public RelayOutput()
        {
            this.idField = "-1";
            this.directionField = RelayDirection.ForwardOnly;
            this.valueField = RelayValue.Off;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        [System.ComponentModel.DefaultValueAttribute("-1")]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "token")]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(RelayDirection.ForwardOnly)]
        public RelayDirection Direction
        {
            get
            {
                return this.directionField;
            }
            set
            {
                this.directionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(RelayValue.Off)]
        public RelayValue Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/RobotSchema.xsd")]
    public enum RelayDirection
    {

        /// <remarks/>
        ForwardOnly,

        /// <remarks/>
        ReverseOnly,

        /// <remarks/>
        Both,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/RobotSchema.xsd")]
    public enum RelayValue
    {

        /// <remarks/>
        Off,

        /// <remarks/>
        Forward,

        /// <remarks/>
        Reverse,

        /// <remarks/>
        On,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
#if NET461
    [System.ComponentModel.DesignerCategoryAttribute("code")]
#endif
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/RobotSchema.xsd")]
    public partial class DigitalInput
    {

        private string idField;

        private string nameField;

        private bool valueField;

        public DigitalInput()
        {
            this.idField = "-1";
            this.valueField = false;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        [System.ComponentModel.DefaultValueAttribute("-1")]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "token")]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
#if NET461
    [System.ComponentModel.DesignerCategoryAttribute("code")]
#endif
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/RobotSchema.xsd")]
    public partial class PWMOutput
    {

        private string idField;

        private string nameField;

        private double valueField;

        public PWMOutput()
        {
            this.idField = "-1";
            this.valueField = 0D;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
        [System.ComponentModel.DefaultValueAttribute("-1")]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "token")]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0D)]
        public double Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
#if NET461
    [System.ComponentModel.DesignerCategoryAttribute("code")]
#endif
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/RobotSchema.xsd")]
    public partial class Subsystem
    {

        private PWMOutput[] pWMOutputField;

        private object[] itemsField;

        private object[] items1Field;

        private RelayOutput[] relayOutputField;

        private CANTalon[] cANTalonsField;

        private PIDControllerSoftware pIDControllerField;

        private string nameField;

        private bool softwarePIDEnabledField;

        public Subsystem()
        {
            this.softwarePIDEnabledField = false;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PWMOutput")]
        public PWMOutput[] PWMOutput
        {
            get
            {
                return this.pWMOutputField;
            }
            set
            {
                this.pWMOutputField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AnalogInput", typeof(AnalogInput))]
        [System.Xml.Serialization.XmlElementAttribute("Potentiometer", typeof(Potentiometer))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DigitalInput", typeof(DigitalInput))]
        [System.Xml.Serialization.XmlElementAttribute("QuadEncoder", typeof(QuadEncoder))]
        public object[] Items1
        {
            get
            {
                return this.items1Field;
            }
            set
            {
                this.items1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RelayOutput")]
        public RelayOutput[] RelayOutput
        {
            get
            {
                return this.relayOutputField;
            }
            set
            {
                this.relayOutputField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CANTalons")]
        public CANTalon[] CANTalons
        {
            get
            {
                return this.cANTalonsField;
            }
            set
            {
                this.cANTalonsField = value;
            }
        }

        /// <remarks/>
        public PIDControllerSoftware PIDController
        {
            get
            {
                return this.pIDControllerField;
            }
            set
            {
                this.pIDControllerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "token")]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool SoftwarePIDEnabled
        {
            get
            {
                return this.softwarePIDEnabledField;
            }
            set
            {
                this.softwarePIDEnabledField = value;
            }
        }
    }
}
