//This File Has Been Modified by XSDFixer
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace Team1922.MVVM.Models {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
#if NET461
    [System.ComponentModel.DesignerCategoryAttribute("code")]
#endif
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://github.com/Team-1922/OzRobotBuilder.NET/blob/master/Models/RobotSchema.xsd" +
        "")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://github.com/Team-1922/OzRobotBuilder.NET/blob/master/Models/RobotSchema.xsd" +
        "", IsNullable=false)]
    public partial class Robot : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Subsystem[] subsystemField;
        
        private Joystick[] joystickField;
        
        private OnChangeEventHandler[] onChangeEventHandlerField;
        
        private OnWithinRangeEventHandler[] onWithinRangeEventHandlerField;
        
        private ContinuousCommand[] continuousCommandField;
        
        private string teamNumberField;
        
        private string analogInputSampleRateField;
        
        public Robot() {
            this.analogInputSampleRateField = "62500";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Subsystem")]
        public Subsystem[] Subsystem {
            get {
                return this.subsystemField;
            }
            set {
                this.subsystemField = value;
                this.RaisePropertyChanged("Subsystem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Joystick")]
        public Joystick[] Joystick {
            get {
                return this.joystickField;
            }
            set {
                this.joystickField = value;
                this.RaisePropertyChanged("Joystick");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OnChangeEventHandler")]
        public OnChangeEventHandler[] OnChangeEventHandler {
            get {
                return this.onChangeEventHandlerField;
            }
            set {
                this.onChangeEventHandlerField = value;
                this.RaisePropertyChanged("OnChangeEventHandler");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OnWithinRangeEventHandler")]
        public OnWithinRangeEventHandler[] OnWithinRangeEventHandler {
            get {
                return this.onWithinRangeEventHandlerField;
            }
            set {
                this.onWithinRangeEventHandlerField = value;
                this.RaisePropertyChanged("OnWithinRangeEventHandler");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ContinuousCommand")]
        public ContinuousCommand[] ContinuousCommand {
            get {
                return this.continuousCommandField;
            }
            set {
                this.continuousCommandField = value;
                this.RaisePropertyChanged("ContinuousCommand");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string TeamNumber {
            get {
                return this.teamNumberField;
            }
            set {
                this.teamNumberField = value;
                this.RaisePropertyChanged("TeamNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        [System.ComponentModel.DefaultValueAttribute("62500")]
        public string AnalogInputSampleRate {
            get {
                return this.analogInputSampleRateField;
            }
            set {
                this.analogInputSampleRateField = value;
                this.RaisePropertyChanged("AnalogInputSampleRate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
#if NET461
    [System.ComponentModel.DesignerCategoryAttribute("code")]
#endif
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://github.com/Team-1922/OzRobotBuilder.NET/blob/master/Models/RobotSchema.xsd" +
        "")]
    public partial class Subsystem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PWMOutput[] pWMOutputField;
        
        private AnalogInput[] analogInputField;
        
        private QuadEncoder[] quadEncoderField;
        
        private DigitalInput[] digitalInputField;
        
        private RelayOutput[] relayOutputField;
        
        private CANTalon[] cANTalonsField;
        
        private PIDControllerSoftware pIDControllerField;
        
        private string nameField;
        
        private bool softwarePIDEnabledField;
        
        public Subsystem() {
            this.softwarePIDEnabledField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PWMOutput")]
        public PWMOutput[] PWMOutput {
            get {
                return this.pWMOutputField;
            }
            set {
                this.pWMOutputField = value;
                this.RaisePropertyChanged("PWMOutput");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AnalogInput")]
        public AnalogInput[] AnalogInput {
            get {
                return this.analogInputField;
            }
            set {
                this.analogInputField = value;
                this.RaisePropertyChanged("AnalogInput");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("QuadEncoder")]
        public QuadEncoder[] QuadEncoder {
            get {
                return this.quadEncoderField;
            }
            set {
                this.quadEncoderField = value;
                this.RaisePropertyChanged("QuadEncoder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DigitalInput")]
        public DigitalInput[] DigitalInput {
            get {
                return this.digitalInputField;
            }
            set {
                this.digitalInputField = value;
                this.RaisePropertyChanged("DigitalInput");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RelayOutput")]
        public RelayOutput[] RelayOutput {
            get {
                return this.relayOutputField;
            }
            set {
                this.relayOutputField = value;
                this.RaisePropertyChanged("RelayOutput");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CANTalons")]
        public CANTalon[] CANTalons {
            get {
                return this.cANTalonsField;
            }
            set {
                this.cANTalonsField = value;
                this.RaisePropertyChanged("CANTalons");
            }
        }
        
        /// <remarks/>
        public PIDControllerSoftware PIDController {
            get {
                return this.pIDControllerField;
            }
            set {
                this.pIDControllerField = value;
                this.RaisePropertyChanged("PIDController");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool SoftwarePIDEnabled {
            get {
                return this.softwarePIDEnabledField;
            }
            set {
                this.softwarePIDEnabledField = value;
                this.RaisePropertyChanged("SoftwarePIDEnabled");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
#if NET461
    [System.ComponentModel.DesignerCategoryAttribute("code")]
#endif
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://github.com/Team-1922/OzRobotBuilder.NET/blob/master/Models/RobotSchema.xsd" +
        "")]
    public partial class PWMOutput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string nameField;
        
        private double valueField;
        
        public PWMOutput() {
            this.idField = "-1";
            this.valueField = 0D;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        [System.ComponentModel.DefaultValueAttribute("-1")]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0D)]
        public double Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
#if NET461
    [System.ComponentModel.DesignerCategoryAttribute("code")]
#endif
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://github.com/Team-1922/OzRobotBuilder.NET/blob/master/Models/RobotSchema.xsd" +
        "")]
    public partial class ContinuousCommand : object, System.ComponentModel.INotifyPropertyChanged {
        
        private EventTarget eventTargetField;
        
        private string nameField;
        
        /// <remarks/>
        public EventTarget EventTarget {
            get {
                return this.eventTargetField;
            }
            set {
                this.eventTargetField = value;
                this.RaisePropertyChanged("EventTarget");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
#if NET461
    [System.ComponentModel.DesignerCategoryAttribute("code")]
#endif
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://github.com/Team-1922/OzRobotBuilder.NET/blob/master/Models/RobotSchema.xsd" +
        "")]
    public partial class EventTarget : object, System.ComponentModel.INotifyPropertyChanged {
        
        private EventTargetType typeField;
        
        private string pathField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public EventTargetType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
                this.RaisePropertyChanged("Path");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://github.com/Team-1922/OzRobotBuilder.NET/blob/master/Models/RobotSchema.xsd" +
        "")]
    public enum EventTargetType {
        
        /// <remarks/>
        ModifyValue,
        
        /// <remarks/>
        FullCSMethod,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
#if NET461
    [System.ComponentModel.DesignerCategoryAttribute("code")]
#endif
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://github.com/Team-1922/OzRobotBuilder.NET/blob/master/Models/RobotSchema.xsd" +
        "")]
    public partial class OnWithinRangeEventHandler : object, System.ComponentModel.INotifyPropertyChanged {
        
        private EventTarget eventTargetField;
        
        private string nameField;
        
        private string watchPathField;
        
        private double minField;
        
        private double maxField;
        
        private bool invertField;
        
        public OnWithinRangeEventHandler() {
            this.invertField = false;
        }
        
        /// <remarks/>
        public EventTarget EventTarget {
            get {
                return this.eventTargetField;
            }
            set {
                this.eventTargetField = value;
                this.RaisePropertyChanged("EventTarget");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string WatchPath {
            get {
                return this.watchPathField;
            }
            set {
                this.watchPathField = value;
                this.RaisePropertyChanged("WatchPath");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double Min {
            get {
                return this.minField;
            }
            set {
                this.minField = value;
                this.RaisePropertyChanged("Min");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double Max {
            get {
                return this.maxField;
            }
            set {
                this.maxField = value;
                this.RaisePropertyChanged("Max");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Invert {
            get {
                return this.invertField;
            }
            set {
                this.invertField = value;
                this.RaisePropertyChanged("Invert");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
#if NET461
    [System.ComponentModel.DesignerCategoryAttribute("code")]
#endif
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://github.com/Team-1922/OzRobotBuilder.NET/blob/master/Models/RobotSchema.xsd" +
        "")]
    public partial class OnChangeEventHandler : object, System.ComponentModel.INotifyPropertyChanged {
        
        private EventTarget eventTargetField;
        
        private string nameField;
        
        private string watchPathField;
        
        private double minDeltaField;
        
        public OnChangeEventHandler() {
            this.minDeltaField = 0D;
        }
        
        /// <remarks/>
        public EventTarget EventTarget {
            get {
                return this.eventTargetField;
            }
            set {
                this.eventTargetField = value;
                this.RaisePropertyChanged("EventTarget");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string WatchPath {
            get {
                return this.watchPathField;
            }
            set {
                this.watchPathField = value;
                this.RaisePropertyChanged("WatchPath");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0D)]
        public double MinDelta {
            get {
                return this.minDeltaField;
            }
            set {
                this.minDeltaField = value;
                this.RaisePropertyChanged("MinDelta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
#if NET461
    [System.ComponentModel.DesignerCategoryAttribute("code")]
#endif
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://github.com/Team-1922/OzRobotBuilder.NET/blob/master/Models/RobotSchema.xsd" +
        "")]
    public partial class JoystickButton : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private bool valueField;
        
        public JoystickButton() {
            this.valueField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
#if NET461
    [System.ComponentModel.DesignerCategoryAttribute("code")]
#endif
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://github.com/Team-1922/OzRobotBuilder.NET/blob/master/Models/RobotSchema.xsd" +
        "")]
    public partial class JoystickAxis : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private double valueField;
        
        public JoystickAxis() {
            this.valueField = 0D;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0D)]
        public double Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
#if NET461
    [System.ComponentModel.DesignerCategoryAttribute("code")]
#endif
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://github.com/Team-1922/OzRobotBuilder.NET/blob/master/Models/RobotSchema.xsd" +
        "")]
    public partial class Joystick : object, System.ComponentModel.INotifyPropertyChanged {
        
        private JoystickAxis[] axisField;
        
        private JoystickButton[] buttonField;
        
        private string nameField;
        
        private string idField;
        
        public Joystick() {
            this.idField = "-1";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Axis")]
        public JoystickAxis[] Axis {
            get {
                return this.axisField;
            }
            set {
                this.axisField = value;
                this.RaisePropertyChanged("Axis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Button")]
        public JoystickButton[] Button {
            get {
                return this.buttonField;
            }
            set {
                this.buttonField = value;
                this.RaisePropertyChanged("Button");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        [System.ComponentModel.DefaultValueAttribute("-1")]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
#if NET461
    [System.ComponentModel.DesignerCategoryAttribute("code")]
#endif
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://github.com/Team-1922/OzRobotBuilder.NET/blob/master/Models/RobotSchema.xsd" +
        "")]
    public partial class PIDControllerSoftware : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double pField;
        
        private bool pFieldSpecified;
        
        private double iField;
        
        private bool iFieldSpecified;
        
        private double dField;
        
        private bool dFieldSpecified;
        
        private double fField;
        
        private bool fFieldSpecified;
        
        private double toleranceField;
        
        private bool toleranceFieldSpecified;
        
        private double cycleDurationField;
        
        private bool cycleDurationFieldSpecified;
        
        private bool continuousField;
        
        private bool continuousFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double P {
            get {
                return this.pField;
            }
            set {
                this.pField = value;
                this.RaisePropertyChanged("P");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PSpecified {
            get {
                return this.pFieldSpecified;
            }
            set {
                this.pFieldSpecified = value;
                this.RaisePropertyChanged("PSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double I {
            get {
                return this.iField;
            }
            set {
                this.iField = value;
                this.RaisePropertyChanged("I");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ISpecified {
            get {
                return this.iFieldSpecified;
            }
            set {
                this.iFieldSpecified = value;
                this.RaisePropertyChanged("ISpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double D {
            get {
                return this.dField;
            }
            set {
                this.dField = value;
                this.RaisePropertyChanged("D");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DSpecified {
            get {
                return this.dFieldSpecified;
            }
            set {
                this.dFieldSpecified = value;
                this.RaisePropertyChanged("DSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double F {
            get {
                return this.fField;
            }
            set {
                this.fField = value;
                this.RaisePropertyChanged("F");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FSpecified {
            get {
                return this.fFieldSpecified;
            }
            set {
                this.fFieldSpecified = value;
                this.RaisePropertyChanged("FSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double Tolerance {
            get {
                return this.toleranceField;
            }
            set {
                this.toleranceField = value;
                this.RaisePropertyChanged("Tolerance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ToleranceSpecified {
            get {
                return this.toleranceFieldSpecified;
            }
            set {
                this.toleranceFieldSpecified = value;
                this.RaisePropertyChanged("ToleranceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double CycleDuration {
            get {
                return this.cycleDurationField;
            }
            set {
                this.cycleDurationField = value;
                this.RaisePropertyChanged("CycleDuration");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CycleDurationSpecified {
            get {
                return this.cycleDurationFieldSpecified;
            }
            set {
                this.cycleDurationFieldSpecified = value;
                this.RaisePropertyChanged("CycleDurationSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Continuous {
            get {
                return this.continuousField;
            }
            set {
                this.continuousField = value;
                this.RaisePropertyChanged("Continuous");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ContinuousSpecified {
            get {
                return this.continuousFieldSpecified;
            }
            set {
                this.continuousFieldSpecified = value;
                this.RaisePropertyChanged("ContinuousSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
#if NET461
    [System.ComponentModel.DesignerCategoryAttribute("code")]
#endif
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://github.com/Team-1922/OzRobotBuilder.NET/blob/master/Models/RobotSchema.xsd" +
        "")]
    public partial class PIDControllerSRX : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double pField;
        
        private bool pFieldSpecified;
        
        private double iField;
        
        private bool iFieldSpecified;
        
        private double dField;
        
        private bool dFieldSpecified;
        
        private double fField;
        
        private bool fFieldSpecified;
        
        private int iZoneField;
        
        private bool iZoneFieldSpecified;
        
        private double closeLoopRampRateField;
        
        private bool closeLoopRampRateFieldSpecified;
        
        private int allowableCloseLoopErrorField;
        
        private bool allowableCloseLoopErrorFieldSpecified;
        
        private CANTalonDifferentiationLevel sourceTypeField;
        
        private bool sourceTypeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double P {
            get {
                return this.pField;
            }
            set {
                this.pField = value;
                this.RaisePropertyChanged("P");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PSpecified {
            get {
                return this.pFieldSpecified;
            }
            set {
                this.pFieldSpecified = value;
                this.RaisePropertyChanged("PSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double I {
            get {
                return this.iField;
            }
            set {
                this.iField = value;
                this.RaisePropertyChanged("I");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ISpecified {
            get {
                return this.iFieldSpecified;
            }
            set {
                this.iFieldSpecified = value;
                this.RaisePropertyChanged("ISpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double D {
            get {
                return this.dField;
            }
            set {
                this.dField = value;
                this.RaisePropertyChanged("D");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DSpecified {
            get {
                return this.dFieldSpecified;
            }
            set {
                this.dFieldSpecified = value;
                this.RaisePropertyChanged("DSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double F {
            get {
                return this.fField;
            }
            set {
                this.fField = value;
                this.RaisePropertyChanged("F");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FSpecified {
            get {
                return this.fFieldSpecified;
            }
            set {
                this.fFieldSpecified = value;
                this.RaisePropertyChanged("FSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int IZone {
            get {
                return this.iZoneField;
            }
            set {
                this.iZoneField = value;
                this.RaisePropertyChanged("IZone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IZoneSpecified {
            get {
                return this.iZoneFieldSpecified;
            }
            set {
                this.iZoneFieldSpecified = value;
                this.RaisePropertyChanged("IZoneSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double CloseLoopRampRate {
            get {
                return this.closeLoopRampRateField;
            }
            set {
                this.closeLoopRampRateField = value;
                this.RaisePropertyChanged("CloseLoopRampRate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CloseLoopRampRateSpecified {
            get {
                return this.closeLoopRampRateFieldSpecified;
            }
            set {
                this.closeLoopRampRateFieldSpecified = value;
                this.RaisePropertyChanged("CloseLoopRampRateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int AllowableCloseLoopError {
            get {
                return this.allowableCloseLoopErrorField;
            }
            set {
                this.allowableCloseLoopErrorField = value;
                this.RaisePropertyChanged("AllowableCloseLoopError");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AllowableCloseLoopErrorSpecified {
            get {
                return this.allowableCloseLoopErrorFieldSpecified;
            }
            set {
                this.allowableCloseLoopErrorFieldSpecified = value;
                this.RaisePropertyChanged("AllowableCloseLoopErrorSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public CANTalonDifferentiationLevel SourceType {
            get {
                return this.sourceTypeField;
            }
            set {
                this.sourceTypeField = value;
                this.RaisePropertyChanged("SourceType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SourceTypeSpecified {
            get {
                return this.sourceTypeFieldSpecified;
            }
            set {
                this.sourceTypeFieldSpecified = value;
                this.RaisePropertyChanged("SourceTypeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://github.com/Team-1922/OzRobotBuilder.NET/blob/master/Models/RobotSchema.xsd" +
        "")]
    public enum CANTalonDifferentiationLevel {
        
        /// <remarks/>
        Displacement,
        
        /// <remarks/>
        Speed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
#if NET461
    [System.ComponentModel.DesignerCategoryAttribute("code")]
#endif
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://github.com/Team-1922/OzRobotBuilder.NET/blob/master/Models/RobotSchema.xsd" +
        "")]
    public partial class CANTalon : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AnalogInput analogInputField;
        
        private QuadEncoder quadEncoderField;
        
        private PIDControllerSRX pIDConfig0Field;
        
        private PIDControllerSRX pIDConfig1Field;
        
        private string idField;
        
        private string nameField;
        
        private bool enabledPIDProfileField;
        
        private CANTalonFeedbackDevice feedbackDeviceField;
        
        private CANTalonControlMode controlModeField;
        
        private CANTalonNeutralMode neutralModeField;
        
        private bool zeroSensorPositionOnIndexEnabledField;
        
        private bool zeroSensorPositionOnRisingEdgeField;
        
        private bool reverseSensorField;
        
        private bool reverseClosedLoopOutputField;
        
        private bool reversePercentVBusOutputField;
        
        private bool forwardLimitSwitchEnabledField;
        
        private bool reverseLimitSwitchEnabledField;
        
        private bool forwardSoftLimitEnabledField;
        
        private bool reverseSoftLimitEnabledField;
        
        private double forwardSoftLimitField;
        
        private double reverseSoftLimitField;
        
        private double nominalForwardVoltageField;
        
        private double nominalReverseVoltageField;
        
        private double peakForwardVoltageField;
        
        private double peakReverseVoltageField;
        
        private double valueField;
        
        public CANTalon() {
            this.idField = "-1";
            this.enabledPIDProfileField = false;
            this.feedbackDeviceField = CANTalonFeedbackDevice.QuadEncoder;
            this.controlModeField = CANTalonControlMode.PercentVbus;
            this.neutralModeField = CANTalonNeutralMode.Coast;
            this.zeroSensorPositionOnIndexEnabledField = false;
            this.zeroSensorPositionOnRisingEdgeField = false;
            this.reverseSensorField = false;
            this.reverseClosedLoopOutputField = false;
            this.reversePercentVBusOutputField = false;
            this.forwardLimitSwitchEnabledField = false;
            this.reverseLimitSwitchEnabledField = false;
            this.forwardSoftLimitEnabledField = false;
            this.reverseSoftLimitEnabledField = false;
            this.forwardSoftLimitField = 0D;
            this.reverseSoftLimitField = 0D;
            this.nominalForwardVoltageField = 0D;
            this.nominalReverseVoltageField = 0D;
            this.peakForwardVoltageField = 12D;
            this.peakReverseVoltageField = -12D;
            this.valueField = 0D;
        }
        
        /// <remarks/>
        public AnalogInput AnalogInput {
            get {
                return this.analogInputField;
            }
            set {
                this.analogInputField = value;
                this.RaisePropertyChanged("AnalogInput");
            }
        }
        
        /// <remarks/>
        public QuadEncoder QuadEncoder {
            get {
                return this.quadEncoderField;
            }
            set {
                this.quadEncoderField = value;
                this.RaisePropertyChanged("QuadEncoder");
            }
        }
        
        /// <remarks/>
        public PIDControllerSRX PIDConfig0 {
            get {
                return this.pIDConfig0Field;
            }
            set {
                this.pIDConfig0Field = value;
                this.RaisePropertyChanged("PIDConfig0");
            }
        }
        
        /// <remarks/>
        public PIDControllerSRX PIDConfig1 {
            get {
                return this.pIDConfig1Field;
            }
            set {
                this.pIDConfig1Field = value;
                this.RaisePropertyChanged("PIDConfig1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        [System.ComponentModel.DefaultValueAttribute("-1")]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool EnabledPIDProfile {
            get {
                return this.enabledPIDProfileField;
            }
            set {
                this.enabledPIDProfileField = value;
                this.RaisePropertyChanged("EnabledPIDProfile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(CANTalonFeedbackDevice.QuadEncoder)]
        public CANTalonFeedbackDevice FeedbackDevice {
            get {
                return this.feedbackDeviceField;
            }
            set {
                this.feedbackDeviceField = value;
                this.RaisePropertyChanged("FeedbackDevice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(CANTalonControlMode.PercentVbus)]
        public CANTalonControlMode ControlMode {
            get {
                return this.controlModeField;
            }
            set {
                this.controlModeField = value;
                this.RaisePropertyChanged("ControlMode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(CANTalonNeutralMode.Coast)]
        public CANTalonNeutralMode NeutralMode {
            get {
                return this.neutralModeField;
            }
            set {
                this.neutralModeField = value;
                this.RaisePropertyChanged("NeutralMode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ZeroSensorPositionOnIndexEnabled {
            get {
                return this.zeroSensorPositionOnIndexEnabledField;
            }
            set {
                this.zeroSensorPositionOnIndexEnabledField = value;
                this.RaisePropertyChanged("ZeroSensorPositionOnIndexEnabled");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ZeroSensorPositionOnRisingEdge {
            get {
                return this.zeroSensorPositionOnRisingEdgeField;
            }
            set {
                this.zeroSensorPositionOnRisingEdgeField = value;
                this.RaisePropertyChanged("ZeroSensorPositionOnRisingEdge");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ReverseSensor {
            get {
                return this.reverseSensorField;
            }
            set {
                this.reverseSensorField = value;
                this.RaisePropertyChanged("ReverseSensor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ReverseClosedLoopOutput {
            get {
                return this.reverseClosedLoopOutputField;
            }
            set {
                this.reverseClosedLoopOutputField = value;
                this.RaisePropertyChanged("ReverseClosedLoopOutput");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ReversePercentVBusOutput {
            get {
                return this.reversePercentVBusOutputField;
            }
            set {
                this.reversePercentVBusOutputField = value;
                this.RaisePropertyChanged("ReversePercentVBusOutput");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ForwardLimitSwitchEnabled {
            get {
                return this.forwardLimitSwitchEnabledField;
            }
            set {
                this.forwardLimitSwitchEnabledField = value;
                this.RaisePropertyChanged("ForwardLimitSwitchEnabled");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ReverseLimitSwitchEnabled {
            get {
                return this.reverseLimitSwitchEnabledField;
            }
            set {
                this.reverseLimitSwitchEnabledField = value;
                this.RaisePropertyChanged("ReverseLimitSwitchEnabled");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ForwardSoftLimitEnabled {
            get {
                return this.forwardSoftLimitEnabledField;
            }
            set {
                this.forwardSoftLimitEnabledField = value;
                this.RaisePropertyChanged("ForwardSoftLimitEnabled");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ReverseSoftLimitEnabled {
            get {
                return this.reverseSoftLimitEnabledField;
            }
            set {
                this.reverseSoftLimitEnabledField = value;
                this.RaisePropertyChanged("ReverseSoftLimitEnabled");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0D)]
        public double ForwardSoftLimit {
            get {
                return this.forwardSoftLimitField;
            }
            set {
                this.forwardSoftLimitField = value;
                this.RaisePropertyChanged("ForwardSoftLimit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0D)]
        public double ReverseSoftLimit {
            get {
                return this.reverseSoftLimitField;
            }
            set {
                this.reverseSoftLimitField = value;
                this.RaisePropertyChanged("ReverseSoftLimit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0D)]
        public double NominalForwardVoltage {
            get {
                return this.nominalForwardVoltageField;
            }
            set {
                this.nominalForwardVoltageField = value;
                this.RaisePropertyChanged("NominalForwardVoltage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0D)]
        public double NominalReverseVoltage {
            get {
                return this.nominalReverseVoltageField;
            }
            set {
                this.nominalReverseVoltageField = value;
                this.RaisePropertyChanged("NominalReverseVoltage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(12D)]
        public double PeakForwardVoltage {
            get {
                return this.peakForwardVoltageField;
            }
            set {
                this.peakForwardVoltageField = value;
                this.RaisePropertyChanged("PeakForwardVoltage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(-12D)]
        public double PeakReverseVoltage {
            get {
                return this.peakReverseVoltageField;
            }
            set {
                this.peakReverseVoltageField = value;
                this.RaisePropertyChanged("PeakReverseVoltage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0D)]
        public double Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
#if NET461
    [System.ComponentModel.DesignerCategoryAttribute("code")]
#endif
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://github.com/Team-1922/OzRobotBuilder.NET/blob/master/Models/RobotSchema.xsd" +
        "")]
    public partial class AnalogInput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string nameField;
        
        private int accumulatorCenterField;
        
        private int accumulatorDeadBandField;
        
        private int accumulatorInitialValueField;
        
        private int averageBitsField;
        
        private int oversampleBitsField;
        
        private double conversionRatioField;
        
        private double sensorOffsetField;
        
        private int rawInputField;
        
        private double convertedInputField;
        
        private long accumulatorCountField;
        
        private long accumulatorValueField;
        
        public AnalogInput() {
            this.idField = "-1";
            this.accumulatorCenterField = 2048;
            this.accumulatorInitialValueField = 0;
            this.conversionRatioField = 1D;
            this.sensorOffsetField = 0D;
            this.rawInputField = 0;
            this.convertedInputField = 0D;
            this.accumulatorCountField = ((long)(0));
            this.accumulatorValueField = ((long)(0));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        [System.ComponentModel.DefaultValueAttribute("-1")]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(2048)]
        public int AccumulatorCenter {
            get {
                return this.accumulatorCenterField;
            }
            set {
                this.accumulatorCenterField = value;
                this.RaisePropertyChanged("AccumulatorCenter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int accumulatorDeadBand {
            get {
                return this.accumulatorDeadBandField;
            }
            set {
                this.accumulatorDeadBandField = value;
                this.RaisePropertyChanged("accumulatorDeadBand");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int AccumulatorInitialValue {
            get {
                return this.accumulatorInitialValueField;
            }
            set {
                this.accumulatorInitialValueField = value;
                this.RaisePropertyChanged("AccumulatorInitialValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int AverageBits {
            get {
                return this.averageBitsField;
            }
            set {
                this.averageBitsField = value;
                this.RaisePropertyChanged("AverageBits");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int OversampleBits {
            get {
                return this.oversampleBitsField;
            }
            set {
                this.oversampleBitsField = value;
                this.RaisePropertyChanged("OversampleBits");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(1D)]
        public double ConversionRatio {
            get {
                return this.conversionRatioField;
            }
            set {
                this.conversionRatioField = value;
                this.RaisePropertyChanged("ConversionRatio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0D)]
        public double SensorOffset {
            get {
                return this.sensorOffsetField;
            }
            set {
                this.sensorOffsetField = value;
                this.RaisePropertyChanged("SensorOffset");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int RawInput {
            get {
                return this.rawInputField;
            }
            set {
                this.rawInputField = value;
                this.RaisePropertyChanged("RawInput");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0D)]
        public double ConvertedInput {
            get {
                return this.convertedInputField;
            }
            set {
                this.convertedInputField = value;
                this.RaisePropertyChanged("ConvertedInput");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(long), "0")]
        public long AccumulatorCount {
            get {
                return this.accumulatorCountField;
            }
            set {
                this.accumulatorCountField = value;
                this.RaisePropertyChanged("AccumulatorCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(long), "0")]
        public long AccumulatorValue {
            get {
                return this.accumulatorValueField;
            }
            set {
                this.accumulatorValueField = value;
                this.RaisePropertyChanged("AccumulatorValue");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
#if NET461
    [System.ComponentModel.DesignerCategoryAttribute("code")]
#endif
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://github.com/Team-1922/OzRobotBuilder.NET/blob/master/Models/RobotSchema.xsd" +
        "")]
    public partial class QuadEncoder : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string iD1Field;
        
        private string nameField;
        
        private double conversionRatioField;
        
        private long rawValueField;
        
        private double valueField;
        
        private double rawVelocityField;
        
        private double velocityField;
        
        public QuadEncoder() {
            this.idField = "-1";
            this.iD1Field = "-1";
            this.conversionRatioField = 1D;
            this.rawValueField = ((long)(0));
            this.valueField = 0D;
            this.rawVelocityField = 0D;
            this.velocityField = 0D;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        [System.ComponentModel.DefaultValueAttribute("-1")]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        [System.ComponentModel.DefaultValueAttribute("-1")]
        public string ID1 {
            get {
                return this.iD1Field;
            }
            set {
                this.iD1Field = value;
                this.RaisePropertyChanged("ID1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(1D)]
        public double ConversionRatio {
            get {
                return this.conversionRatioField;
            }
            set {
                this.conversionRatioField = value;
                this.RaisePropertyChanged("ConversionRatio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(long), "0")]
        public long RawValue {
            get {
                return this.rawValueField;
            }
            set {
                this.rawValueField = value;
                this.RaisePropertyChanged("RawValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0D)]
        public double Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0D)]
        public double RawVelocity {
            get {
                return this.rawVelocityField;
            }
            set {
                this.rawVelocityField = value;
                this.RaisePropertyChanged("RawVelocity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0D)]
        public double Velocity {
            get {
                return this.velocityField;
            }
            set {
                this.velocityField = value;
                this.RaisePropertyChanged("Velocity");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://github.com/Team-1922/OzRobotBuilder.NET/blob/master/Models/RobotSchema.xsd" +
        "")]
    public enum CANTalonFeedbackDevice {
        
        /// <remarks/>
        QuadEncoder,
        
        /// <remarks/>
        AnalogPotentiometer,
        
        /// <remarks/>
        AnalogEncoder,
        
        /// <remarks/>
        EncoderRising,
        
        /// <remarks/>
        EncoderFalling,
        
        /// <remarks/>
        CtreMagEncoderRelative,
        
        /// <remarks/>
        CtreMagEncoderAbsolute,
        
        /// <remarks/>
        PulseWidth,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://github.com/Team-1922/OzRobotBuilder.NET/blob/master/Models/RobotSchema.xsd" +
        "")]
    public enum CANTalonControlMode {
        
        /// <remarks/>
        PercentVbus,
        
        /// <remarks/>
        Position,
        
        /// <remarks/>
        Speed,
        
        /// <remarks/>
        Current,
        
        /// <remarks/>
        Voltage,
        
        /// <remarks/>
        Follower,
        
        /// <remarks/>
        MotionProfile,
        
        /// <remarks/>
        Disabled,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://github.com/Team-1922/OzRobotBuilder.NET/blob/master/Models/RobotSchema.xsd" +
        "")]
    public enum CANTalonNeutralMode {
        
        /// <remarks/>
        Jumper,
        
        /// <remarks/>
        Brake,
        
        /// <remarks/>
        Coast,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
#if NET461
    [System.ComponentModel.DesignerCategoryAttribute("code")]
#endif
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://github.com/Team-1922/OzRobotBuilder.NET/blob/master/Models/RobotSchema.xsd" +
        "")]
    public partial class RelayOutput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string nameField;
        
        private RelayDirection directionField;
        
        private RelayValue valueField;
        
        public RelayOutput() {
            this.idField = "-1";
            this.directionField = RelayDirection.ForwardOnly;
            this.valueField = RelayValue.Off;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        [System.ComponentModel.DefaultValueAttribute("-1")]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(RelayDirection.ForwardOnly)]
        public RelayDirection Direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
                this.RaisePropertyChanged("Direction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(RelayValue.Off)]
        public RelayValue Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://github.com/Team-1922/OzRobotBuilder.NET/blob/master/Models/RobotSchema.xsd" +
        "")]
    public enum RelayDirection {
        
        /// <remarks/>
        ForwardOnly,
        
        /// <remarks/>
        ReverseOnly,
        
        /// <remarks/>
        Both,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://github.com/Team-1922/OzRobotBuilder.NET/blob/master/Models/RobotSchema.xsd" +
        "")]
    public enum RelayValue {
        
        /// <remarks/>
        Off,
        
        /// <remarks/>
        Forward,
        
        /// <remarks/>
        Reverse,
        
        /// <remarks/>
        On,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
#if NET461
    [System.ComponentModel.DesignerCategoryAttribute("code")]
#endif
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://github.com/Team-1922/OzRobotBuilder.NET/blob/master/Models/RobotSchema.xsd" +
        "")]
    public partial class DigitalInput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string nameField;
        
        private bool valueField;
        
        public DigitalInput() {
            this.idField = "-1";
            this.valueField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        [System.ComponentModel.DefaultValueAttribute("-1")]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
}
